### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by ElleEntertainment** [darki73/FreedomCore#1]
What i have done:
- Installed database (freedomcore-12-06-2015-13-00.sql)
- modified Core/Configuration/Configuration.php
- give all permission the freedomcore folder
- go to Google Chrome and type "localhost/freedomcore"
- I have a blank page
- I've gone to see html code and it is empty, it doesn't load anything

**Comment by darki73** [comment]
You need to install it to root directory of your webserver.
Grant 755 Recurcive permissions on Cache and Uploads folders.
You also need to have curl extensions installed in order to be able to use FreedomCore

**Comment by Orangs** [comment]
I have too issue on my Debian 7 webserver. How i can fix it? I have still blank page and anything load. Can you give me some instructions how to fix? I will find on google, debian maybe have problems with Smarty. Thanks for answer/help

here is a comment from my log:
[Tue Jun 23 01:30:55 2015] [error] [client X.XXX.XXX.X] PHP Fatal error:  require_once(): Failed opening required '/Core/Core.php' (include_path='.:/usr/share/php:/usr/share/pear') in /domains/inspire-gaming.cz/subdomains/unholy/index.php on line 2

**Comment by darki73** [comment]
Fixed in https://github.com/darki73/FreedomCore/commit/42ec6189976ecc792a3956b903ffdd351003e303

**Comment by ElleEntertainment** [comment]
rev: https://github.com/darki73/FreedomCore/commit/5d5942a8010dfd38b551c4e7422641bbb1a3c1f8

I'm on windows:
![immagine](https://cloud.githubusercontent.com/assets/10599040/8301671/59d38710-1990-11e5-818e-895bccb62fb8.png)

**Comment by Orangs** [comment]
rev: 42ec618

Im on Debian 7 and i have still blank page. Config is right and CHMODs too.
![image](https://cloud.githubusercontent.com/assets/2785697/8310307/4de5abe2-19cf-11e5-8b8b-f5145295741f.png)

**Comment by darki73** [comment]
enable curl, as i already said and edit .htaccess to display errors

**Comment by ElleEntertainment** [comment]
i have enabled curl (and restarted apache):
![cattura](https://cloud.githubusercontent.com/assets/10599040/8310511/b5c4f94c-19d0-11e5-844d-6b48d72cb678.PNG)

**Comment by darki73** [comment]
@VirusEntertainment as i said, modify htaccess for displaying errors, or i wont be able to help

**Comment by Orangs** [comment]
I modified htacces for displaying errors and i have this errors.

![image](https://cloud.githubusercontent.com/assets/2785697/8310608/54b737b8-19d1-11e5-9736-9917519bf769.png)

**Comment by ElleEntertainment** [comment]
Fatal error: Uncaught --> Smarty: Unable to read config file 'Italian.language' <-- thrown in E:\Raccolte\repacks\Jeuties Blizzlike Repack 9.8.3\Server\www\FreedomCore\Core\Libraries\Smarty\sysplugins\smarty_internal_resource_file.php on line 68

i modified all access so it cant be the problem

**Comment by Orangs** [comment]
I think, we need set up CHMODS on another files or folders, but i dont know the files/folders.

**Comment by darki73** [comment]
1. Wrong chmod on cache folder
2. There is no Italian language

**Comment by ElleEntertainment** [comment]
ok so how can i set a working language?

**Comment by darki73** [comment]
There is only Russian atm

**Comment by ElleEntertainment** [comment]
OK but HOW can i set the russian language as default? in configuration.php i can't see nothing

**Comment by Orangs** [comment]
I have still problem. I have modified htacces for displaying errors and i have no errors but i have still Blank Page. How i can fix it?

**Comment by darki73** [comment]
Update to rev. https://github.com/darki73/FreedomCore/commit/6dfbaf9a9f4a156d7171722d76c7e1db581b1755  
and report back if you will see any text there

**Comment by ElleEntertainment** [comment]
I have "unexpected '[' " errors in this files:
Items.Freedomcore.php -> line 1109, 34
Characters.Freedomcore.php -> line 305 to 309, 44 to 46, 
Account.Freedomcore -> line 262

I don't know why it is an error because the syntax should be fine..

**Comment by darki73** [comment]
Updated repo, try to update yours.

And please guys, start using Git (There is git for windows -> http://windows.github.com), coz i've seen someone here just downloading zip archive

**Comment by ElleEntertainment** [comment]
i'm using git XD 

btw updated to rev https://github.com/darki73/FreedomCore/commit/d41106b38c7e619f64f4171a1ec22c87b90d5e6a

Errors: unexpected '[' etc... at the same files.. now Account.Freedomcore -> line 288, if other files changed, so probably the line number is changed too, but the error code is the same

**Comment by darki73** [comment]
@VirusEntertainment probably its your server error. Website is now working on 3 different machines with different configurations straight from git repo
