### ISSUE TITLE
Can't find a text

### ISSUE THREAD

**Issue by ElleEntertainment** [darki73/FreedomCore#12]
What is the file where i can find this text to translate? 
![schermata 2015-07-04 alle 14 05 35](https://cloud.githubusercontent.com/assets/10599040/8507849/d0f26cbc-2255-11e5-9b3a-1311dd0f5f7a.png)

**Comment by darki73** [comment]
i guess its hardcoded, ill take a look

**Comment by CrisPj** [comment]
https://github.com/darki73/FreedomCore/blob/master/Templates/FreedomCore/header.tpl#L161
