### ISSUE TITLE
Bug language

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#16]
Hello I found a bug, if a new user comes to the site and in the footer spawn that language is not defined and then on the Web because problémy.Ale when it selects everything works as it should.

**Comment by darki73** [comment]
No idea what are you talking about, please write it in your native language and provide screenshots

**Comment by jAKErCZ** [comment]
I'm sorry, I'm doing the translation for the Czech language here attach the picture ->
http://ctrlv.cz/tifb
It happens when you need to clear the cookie, and when it is there so that does not work most of the things that are on the site.
