### ISSUE TITLE
MySQL connections

### ISSUE THREAD

**Issue by Ardinis** [darki73/FreedomCore#17]
There is a huge problem with MySQL connection, the website opens for each user all the connections in Database.FreedomCore.php to mysql server.
After several connected users, mysql display an error (although it can be bypassed)

**Comment by Ardinis** [comment]
Works better without persistent connections : <code>PDO::ATTR_PERSISTENT => false</code>

**Comment by darki73** [comment]
Fixed in https://github.com/darki73/FreedomCore/commit/96ac6e50b764033838dd9d04242756a33d6a8b45
