### ISSUE TITLE
Not to sign and not to choose language

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#18]
Hello, again I found another mistake. It's not log into the system and not plus also select the language.

**Comment by jAKErCZ** [comment]
Look --> http://ctrlv.cz/J0X7 = can not choose the language and  can not log in.

**Comment by darki73** [comment]
1. How log in related to language
2. Mention revision
3. How to reproduce issue

Next time without that info I simply won't answer and will definitely close the issue

**Comment by jAKErCZ** [comment]
I'm sorry, I discovered that if the user has selected language as in the photo can not log into the system, before it was possible to select the language but at the moment when I choose a language does not make any changes. So I hope that it will somehow fix.

**Comment by darki73** [comment]
I'm closing the issue, you totally ignored me.
Issues about the same thing will be ignored from now on
