### ISSUE TITLE
The problem with installing

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#19]
The problem is that when you download a new kernel FreedomCore and you want to install the browser and redirects you to at www.foo.com/install but that's it because the viewer writes, "This page has a redirect loop '

**Comment by darki73** [comment]
Closed, everything works

**Comment by jAKErCZ** [comment]
No look = http://unholy.inspire-gaming.cz/

**Comment by darki73** [comment]
![default](https://cloud.githubusercontent.com/assets/1318627/8966801/032be574-363c-11e5-9f46-97d3059d32e4.PNG)
CLOSED!
