### ISSUE TITLE
change language

### ISSUE THREAD

**Issue by Ardinis** [darki73/FreedomCore#2]
There is an issue with changing the language with the menu at the end of the page, the variable  <code>$_SESSION['preferredlanguage']</code> (Utilities.FreedomCore.php:8) isn't defined whereas it's set in parser.php in <code>changelanguage</code> case.

**Comment by Nelidon** [comment]
The problem came from my wod core, I fixed it.
You can close it :+1:

**Comment by darki73** [comment]
@Nelidon thx, will fix it soon

**Comment by darki73** [comment]
Fixed in https://github.com/darki73/FreedomCore/commit/6eeed825bfdaae724803ccdf780be841d44f5b7e
