### ISSUE TITLE
Automatic import database

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#20]
I do not know whether the databases are recorded manually but I feel that the installers it is done as automatically and unfortunately it is not working. Still loaded and no progress.

Error: Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by darki73** [comment]
**the server responded with a status of 500 (Internal Server Error)**
Problem of your server, everything works fine.
1. No PHP error log
2. No screenshots
3. No correct description

**CLOSED**
