### ISSUE TITLE
Automatic import database

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#21]
According to information from the database could be imported into a database automatically after clicking. But it will not happen, and it throws these errors.

PHP ERROR:

[Wed Jul 29 21:46:12 2015] [error] [client 85.71.70.196] PHP Notice:  Undefined index: Database in /domains/inspire-gaming.cz/subdomains/unholy/install.php on line 101, referer: http://unholy.inspire-gaming.cz/install
[Wed Jul 29 21:46:12 2015] [error] [client 85.71.70.196] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2019] Can't initialize character set  (path: /usr/share/mysql/charsets/)' in /domains/inspire-gaming.cz/subdomains/unholy/Core/Extensions/Installer.FreedomCore.php:20\nStack trace:\n#0 /domains/inspire-gaming.cz/subdomains/unholy/Core/Extensions/Installer.FreedomCore.php(20): PDO->__construct('mysql:host=;dbn...', NULL, NULL, Array)\n#1 /domains/inspire-gaming.cz/subdomains/unholy/install.php(101): Installer::Import(NULL, NULL, NULL, NULL, NULL, '/domains/inspir...')\n#2 {main}\n  thrown in /domains/inspire-gaming.cz/subdomains/unholy/Core/Extensions/Installer.FreedomCore.php on line 20, referer: http://unholy.inspire-gaming.cz/install

Screenshot here:
http://www.imgup.cz/image/PhO

I hope that everything is already as wanted in order.

**Comment by darki73** [comment]
It says it can't initialize charset. After it complains about absence of Database index inside config file. Make sure script is allowed to write to configuration directory

**Comment by jAKErCZ** [comment]
You mean configuration.php to be writable? or how can I fix it did not do so?Here I did everything exactly as you typed in the instructions
