### ISSUE TITLE
5.4.8 DBCExtractor error

### ISSUE THREAD

**Issue by Orfeous** [darki73/FreedomCore#23]
Generate_Icons_5_4_8.php gives me the following error

Reading icons list from ItemDisplayInfo.dbc...
Looking for icons in data/...
Incorrect format string specified for file data/5.4.8/DBC/ItemDisplayInfo.dbc
(recordCount=64622 fieldCount=26 recordSize=104 stringSize=1650085)

rev: 69e274d7b8d61f7c2fa8dd237e73e6ad3791e694

**Comment by darki73** [comment]
Unfortunately i don't have 5.4.8 dbc right now to test it out
