### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by bonny1992** [darki73/FreedomCore#24]
PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes)

Sadly this is the message I get trying to use your (I hope so) awesome CMS.
Obviously I'm not going to raise my memory only for that, since I work in a very strict network.

**Comment by darki73** [comment]
There is something wrong with your PHP configuration. Script uses max of 15MB of memory on professions page.

**Comment by darki73** [comment]
No further participation.... Closing issue
