### ISSUE TITLE
Project die or no?

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#27]
Hello, I know that the tot does not belong directly to the issue but I would ask that I noticed for the last time that the project has not developed or may I know why it suspended? I know what day it nazačátku new update and now need up to 2 weeks.

The project will continue Poor you terminate?

**Comment by darki73** [comment]
Project is closed for unknown period of time due to lack of interest from users and poor bug submission process. Srsly, i dont want to work on something that has no interest from public.
Now im doing the other project, which i'll be selling. So unless people show interest to this project, it wil be in a "semi closed" state

**Comment by fanaticus** [comment]
Дарки, Дай содержимое файла http://project.freedomcore.ru/notify.php

**Comment by darki73** [comment]
@fanaticus скинуть не могу (файла нет с момента комментирования функции в ядре). Он брал ip, URL сервера и версию ядра и заносил в базу. Это планировалось использоваться для "быстрого" решения проблем с ядром (типо мой адрес такой то, не работает то то). Я смотрел бы на ревизию и давал отвеь

**Comment by jAKErCZ** [comment]
I would have liked to help, I'm willing to look for bugs and errors? It would be possible due to continue in this marvelous system?

**Comment by fanaticus** [comment]
darki73, это я понял ( что он передавал данные ) я хотел сделать лицензию по этой функции. Но уже сделал по другому. http://explosione.ru/ Основной упор делаю в WOD

**Comment by darki73** [comment]
@fanaticus могу я просто ради любопытства поинтересоваться? Зачем вам лицензия? Собрались продавать?

**Comment by jAKErCZ** [comment]
@darki73 I could therefore help develop and give those I have regular bug report? I do not want to stop development.

**Comment by fanaticus** [comment]
@darki73 Не то чтобы продавать, а не использовали в своих целях, ну и естественно что бы не продавали. Лицензию выдаю бесплатно.

**Comment by fanaticus** [comment]
@jAKErCZ Please email me on Skype: fanaticus33rus

**Comment by darki73** [comment]
@fanaticus В таком случае вы противоречите самому себе. То есть вы собираетесь выдавать лицензию по своему усмотрению? Флаг вам в руки и удачи с развитием проекта. Это в корне противоречит тому, с каким подходом я относился к проекту. 

Выдача "лицензии" подразумевает закрытый код и прочее, проект официально закрыт

**Comment by jAKErCZ** [comment]
@darki73 No, aborting it, I think that this system has tremendous potential to become good. Every time someone develops a replica of an official site it will never leave undone. I thought that you enjoy it and especially the system is truly luxurious.

**Comment by fanaticus** [comment]
@darki73 Код открытый. Закрыты лишь пару файлов. Лицензию выдаю ВСЕМ. Как вам объяснить ?
