### ISSUE TITLE
Login error and Characters error

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#3]
Hi, So I figured out that if you're in the login and you enter bad data appears white page. Also, if you give checkbox Remember so you do not login.

After logging in does not display the characters that you own.

**Comment by darki73** [comment]
1. Fixed in  https://github.com/darki73/FreedomCore/commit/e2dae6a04eb3f68bfa6dc37765ce64897a9c8433 
2. Core needs to be installed on clean auth database, because when you create site account, it also creates game account
