### ISSUE TITLE
Importing Database ? Where is the main SQL file that I have  to import ?

### ISSUE THREAD

**Issue by ghost** [darki73/FreedomCore#30]

**Comment by darki73** [comment]
What can I say.... don't use it then... in readme  I clearly stated that this is no production version, so if you have no knowledge then don't use it

**Comment by darki73** [comment]
@Maxxgold ,Sorry for being rude, but its been a long day. I've been working on that installer for last few hours.
I've updated Readme, so now it shouldn't be a problem.

Have a nice day.

**Comment by ghost** [comment]
It's ok, I understand when you are doing all of the work and you have to deal with people on top of that.  I'm still in the learning phase for most of this stuff so it gets frustrating on my end sometimes too. Thank you for all your hard work !

**Comment by darki73** [comment]
@Maxxgold anytime mate. I'm here to help you =)
