### ISSUE TITLE
It's not extract icons

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#4]
Hello, no matter how I try I try I can not extract icons, from dbc files. It looks like this is zaptat what I am doing wrong?

Reading icons list from ItemDisplayInfo.dbc...
Looking for icons in data/...
57986 icons found
Done
Status:
  Not Found: 42945

Reading icons list from SpellIcon.dbc...
Looking for icons in data/...
3226 icons found
Done
Status:
  Not Found: 3226

**Comment by darki73** [comment]
You need also extract interface folder from client (not the addons one), there should be icons folder.
Everything working, so its not an issue

**Comment by jAKErCZ** [comment]
But they are in the folder icon did .... I simply uploaded into a folder dbc 3.3.5a / DBC and then started the generator and nothing ..

**Comment by darki73** [comment]
You need to extract Interface folder from WoW Data files

**Comment by jAKErCZ** [comment]
Like, wow folder interface of refunds into the interface extractor? I've tried it and nothing.

**Comment by Ardinis** [comment]
I have the same issue with DBC & Icons (extracted from .data files) from 6.1.2 patch

**Comment by darki73** [comment]
Fixed in rev. https://github.com/darki73/FreedomCore/commit/6e9a9a4c194c227692d45519971c39090ab7f6e3
