### ISSUE TITLE
error in my apache log:

### ISSUE THREAD

**Issue by UltimateTomatoes** [darki73/FreedomCore#44]
PHP Fatal error:  Call to a member function prepare() on null in /var/www/wow.trinarycs.com/Core/Extensions/News.FreedomCore.php on line 18

**Comment by darki73** [comment]
It's an error in YOUR apache log, solve it yourself. Main website running latest version straight from repo, and having no issues.

If you decided to "cheat" during installation period and disabled some checks, then dont ask why something does not working
