### ISSUE TITLE
Webiste does not work in a different folder

### ISSUE THREAD

**Issue by jAKErCZ** [darki73/FreedomCore#5]
I found one problem and that is that if you do not have an application in the root websites but perhaps in your website is down because it can not retrieve the application source.

Solutions / Templates / change to ./Templates/

And then everything is OK .. it would be possible to adjust please.

**Comment by ElleEntertainment** [comment]
confirm. At the moment i'm writing, users must install this CMS in the root folder of the server. This choice is not the best one, since one user could have more than one website on the server.

**Comment by Ardinis** [comment]
You can create Virtual Host on apache2

**Comment by darki73** [comment]
@VirusEntertainment i have 7 sites, in 7 folders, with 7 virtualhosts

**Comment by jAKErCZ** [comment]
I create virtual host and website say: SQLSTATE[08004] [1040] Too many connections

How to fix?

**Comment by Ardinis** [comment]
Change the max_connexion_limit in mysql

**Comment by jAKErCZ** [comment]
I tried it and nothing ..

**Comment by Ardinis** [comment]
Did you restart mysql ?

**Comment by jAKErCZ** [comment]
Yes, after I restart mysql always fall so I do not what to do.

**Comment by darki73** [comment]
Install MySQL Workbench and send me the Dashboard Page (Under performance tab in sidebar)
![default](https://cloud.githubusercontent.com/assets/1318627/8451422/bff536ca-2015-11e5-9519-b8da51d3f718.PNG)

**Comment by jAKErCZ** [comment]
Ok, lock i fixed to mysql problem.
